
import React from 'react';
import { Link } from 'react-router-dom';
import { Film, Tv, Star, Clapperboard } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SignInButton, SignUpButton, useAuth } from '@clerk/clerk-react';
import { Navigate } from 'react-router-dom';

const Landing = () => {
  const { isSignedIn } = useAuth();

  if (isSignedIn) {
    return <Navigate to="/home" replace />;
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-sky-800 to-indigo-900 flex flex-col">
      {/* Hero Section */}
      <div className="flex-1 flex flex-col items-center justify-center px-4 text-center relative overflow-hidden">
        {/* Background film elements */}
        <div className="absolute inset-0 overflow-hidden opacity-20">
          <div className="absolute -rotate-12 left-1/4 top-1/4">
            <Film className="h-32 w-32 text-amber-300" />
          </div>
          <div className="absolute rotate-12 right-1/4 top-1/3">
            <Clapperboard className="h-40 w-40 text-amber-300" />
          </div>
          <div className="absolute -rotate-6 left-1/3 bottom-1/4">
            <Star className="h-20 w-20 text-amber-300" />
          </div>
          <div className="absolute rotate-12 right-1/3 bottom-1/3">
            <Tv className="h-24 w-24 text-amber-300" />
          </div>
          <div className="absolute -rotate-12 left-2/3 top-1/2">
            <Film className="h-36 w-36 text-amber-300" />
          </div>
        </div>
        
        <div className="mb-8 flex items-center relative z-10">
          <Film className="h-12 w-12 text-amber-400 mr-2" />
          <h1 className="text-4xl md:text-6xl font-bold text-white">
            Flix<span className="text-amber-400">Hive</span>
          </h1>
        </div>
        
        <h2 className="text-xl md:text-2xl text-white/90 mb-6 max-w-2xl relative z-10">
          Find out what to watch, with the best reviews and ratings
        </h2>
        
        <p className="text-white/80 mb-12 max-w-xl relative z-10">
          Discover new movies, get personalized recommendations, and join a community of movie enthusiasts.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-4 relative z-10">
          <SignUpButton mode="modal">
            <Button size="lg" className="border-white/30 text-white hover:bg-white/10 bg-transparent border">
              Get Started
            </Button>
          </SignUpButton>
          
          <SignInButton mode="modal">
            <Button size="lg" variant="outline" className="border-white/30 text-white hover:bg-white/10">
              Sign In
            </Button>
          </SignInButton>
        </div>
      </div>
      
      {/* Features Section */}
      <div className="py-12 px-4 bg-indigo-950/80 backdrop-blur-sm">
        <div className="container mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="p-6 rounded-lg bg-sky-900/60 border border-sky-700/30 shadow-lg hover:shadow-xl transition-shadow">
              <h3 className="text-xl font-semibold text-amber-300 mb-3">AI-Powered Reviews</h3>
              <p className="text-white/90">Get insightful movie reviews generated by our AI from trusted sources.</p>
            </div>
            
            <div className="p-6 rounded-lg bg-sky-900/60 border border-sky-700/30 shadow-lg hover:shadow-xl transition-shadow">
              <h3 className="text-xl font-semibold text-amber-300 mb-3">Personalized Recommendations</h3>
              <p className="text-white/90">Discover movies tailored to your preferences and viewing history.</p>
            </div>
            
            <div className="p-6 rounded-lg bg-sky-900/60 border border-sky-700/30 shadow-lg hover:shadow-xl transition-shadow">
              <h3 className="text-xl font-semibold text-amber-300 mb-3">Track Your Watchlist</h3>
              <p className="text-white/90">Save movies to watch later and keep track of what you've seen.</p>
            </div>
          </div>
        </div>
      </div>
      
      {/* Footer */}
      <footer className="py-6 bg-indigo-950 text-center text-white/60">
        <p>© 2025 <a href="https://www.flixhive.in" className="hover:text-amber-400 transition-colors">www.flixhive.in</a> - PineGrass Tech</p>
      </footer>
    </div>
  );
};

export default Landing;
